service: create-stock-price-index

provider:
  name: aws
  runtime: python3.7
  region: ap-northeast-1

plugins:
  - serverless-python-requirements

functions:
  get-policy-number-list:
    handler: app.lambda_handler
    events:
      - http:
          path: /
          method: get
          integration: lambda
          request:
            template:
              application/json: '{ "user_id" : "$input.params("password")" }'